# Generated by Django 3.2.9 on 2022-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
