# Generated by Django 3.2.9 on 2022-10-16 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStockHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dob', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
