# Generated by Django 3.2.9 on 2022-10-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categorystockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorystockhistory',
            old_name='quantity',
            new_name='clothing',
        ),
        migrations.RemoveField(
            model_name='categorystockhistory',
            name='name',
        ),
        migrations.AddField(
            model_name='categorystockhistory',
            name='electronic',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorystockhistory',
            name='furniture',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
