# Generated by Django 3.2.9 on 2022-10-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221016_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorystockhistory',
            old_name='dob',
            new_name='date',
        ),
    ]
