# Generated by Django 3.2.9 on 2022-10-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_dob_categorystockhistory_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryStockHistory',
        ),
    ]
