# Generated by Django 3.2.9 on 2022-10-16 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_categorystockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStockHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('clothing', models.IntegerField()),
                ('furniture', models.IntegerField()),
                ('electronic', models.IntegerField()),
            ],
        ),
    ]
