# Generated by Django 3.2.9 on 2022-10-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_categorystockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystockhistory',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
