# Generated by Django 4.0.4 on 2022-10-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dynamicpricing_alter_categorystockhistory_clothing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicPricing',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
